# Bryan Fritsch tests run for the paper.

python bryan_fritsch_varied_mX.py --conservative_transport=True --order=1
python bryan_fritsch_varied_mX.py --order=1
python bryan_fritsch_varied_mX.py --conservative_transport=True --order=0
python bryan_fritsch_varied_mX.py --order=0
