# Bryan Fritsch tests run for the paper.

python bryan_fritsch_varied_mX.py --conservative_transport=True --order=1
python bryan_fritsch_varied_mX.py --order=1
python bryan_fritsch_varied_mX.py --conservative_transport=True --order=0
python bryan_fritsch_varied_mX.py --order=0

# Figure plotting scripts for the paper
python plot_bryan_fritsch_Td_over_time.py
python plot_bubble_comps.py
