# NL_slice tests run for the paper

convergence_order_1:
    python NL_slice.py --conservative_transport=True --configuration=convergence --order=1 --ncells_1d=100
    python NL_slice.py --conservative_transport=True --configuration=convergence --order=1 --ncells_1d=140
    python NL_slice.py --conservative_transport=True --configuration=convergence --order=1 --ncells_1d=160
    python NL_slice.py --conservative_transport=True --configuration=convergence --order=1 --ncells_1d=180
    python NL_slice.py --configuration=convergence --order=1 --ncells_1d=100
    python NL_slice.py --configuration=convergence --order=1 --ncells_1d=140
    python NL_slice.py --configuration=convergence --order=1 --ncells_1d=160
    python NL_slice.py --configuration=convergence --order=1 --ncells_1d=180