# Bryan fritch tests run for the paper.

python bryan_fritsch.py --conservative_tranport=True --order=1
python bryan_fritsch.py --order=1
python bryan_fritsch.py --conservative_tranport=True --order=0
python bryan_fritsch.py --order=0